version: "3.2"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_MASTER_KEY
    volumes:
      - .:/app
      - bundle-data:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails db:create db:migrate RAILS_ENV=test

  db:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data:
    driver: local
  bundle-data:
    driver: local