version: "3.2"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_MASTER_KEY
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

  db:
    image: mysql:5.7.26
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data:
    driver: local