FROM ruby:2.6.3-alpine3.10 AS builder

RUN apk add --no-cache alpine-sdk \
    yarn \
    nodejs \
    tzdata \
    mysql-client \
    mysql-dev \
    imagemagick \
    less

WORKDIR /tmp
COPY Gemfile $APP_ROOT
COPY Gemfile.lock $APP_ROOT

RUN bundle install

FROM ruby:2.6.3-alpine3.10

RUN apk add --no-cache alpine-sdk \
    yarn \
    nodejs \
    tzdata \
    mysql-client \
    mysql-dev \
    imagemagick \
    less

COPY --from=builder /usr/local/bundle /usr/local/bundle

WORKDIR /app