version: "3.2"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # environment:
    #   - RAILS_MASTER_KEY
    volumes:
      - .:/app
      - bundle-data:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: /bin/sh -c "bundle exec rails db:create db:migrate RAILS_ENV=test && bundle exec rails s -p 3000 -b '0.0.0.0'"

  db:
    image: mysql:5.7.26
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data:
    driver: local
  bundle-data:
    driver: local