version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11

jobs:
  test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Run tests
          command: |
            export RAILS_MASTER_KEY=${RAILS_MASTER_KEY} &&\
            docker-compose up


workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - test
      # - aws-ecr/build-and-push-image:
      #     requires:
      #       - test
      #     repo: ${MY_REPO_PREFIX}
      #     extra-build-args: --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      #     filters:
      #       branches:
      #         only: circleci-setting
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     family: ${MY_APP_PREFIX}
      #     cluster-name: ${MY_APP_PREFIX}
      #     container-image-name-updates: 'container=${CONTAINER_NAME},tag=latest'